// The public error contract. Codes and their HTTP statuses are fixed.

export const ERROR_HTTP_STATUS = {
  VALIDATION_ERROR: 400,
  INVALID_IDEMPOTENCY_KEY: 400,

  INTENT_NOT_FOUND: 404,

  IDEMPOTENCY_KEY_REUSED: 409,
  INVALID_INTENT_STATE: 409,
  INTENT_EXPIRED: 409,
  ACCOUNT_NOT_QUIESCENT: 409,
  ACCOUNT_BUSY: 409,
  SIGNATURE_ALREADY_ATTACHED: 409,

  ACCOUNT_NOT_FOUND: 422,
  TRANSACTION_BUILD_INVALID: 422,
  SIMULATION_REJECTED: 422,
  INVALID_SIGNED_TRANSACTION: 422,
  SIGNED_TRANSACTION_MISMATCH: 422,
  INVALID_SIGNATURE: 422,
  SIGNER_NOT_AUTHORIZED: 422,

  FEE_TOO_HIGH: 503,
  XRPL_UNAVAILABLE: 503,
  SERVICE_NOT_READY: 503,

  INTERNAL_ERROR: 500,
} as const;

export type ErrorCode = keyof typeof ERROR_HTTP_STATUS;

export const ERROR_CODES = Object.keys(ERROR_HTTP_STATUS) as ErrorCode[];
